SELECT
  p.SPECIFIC_SCHEMA AS SchemaName,
  p.SPECIFIC_NAME AS StoredProcedureName,
  p.PARAMETER_NAME AS ParameterName,
  p.PARAMETER_MODE AS ParameterMode,
  p.DATA_TYPE AS ParameterType,
  p.ORDINAL_POSITION AS ParameterPosition,
  p.USER_DEFINED_TYPE_SCHEMA AS UserDefinedTypeSchema,
  p.USER_DEFINED_TYPE_NAME AS UserDefinedTypeName
FROM INFORMATION_SCHEMA.ROUTINES r
LEFT JOIN INFORMATION_SCHEMA.PARAMETERS p
	ON r.SPECIFIC_SCHEMA = p.SPECIFIC_SCHEMA
	AND r.SPECIFIC_NAME = p.SPECIFIC_NAME
WHERE
  p.SPECIFIC_NAME IS NOT NULL
GROUP BY
  p.SPECIFIC_SCHEMA,
  p.SPECIFIC_NAME,
  p.PARAMETER_NAME,
  p.PARAMETER_MODE,
  p.DATA_TYPE,
  p.ORDINAL_POSITION,
  p.USER_DEFINED_TYPE_SCHEMA,
  p.USER_DEFINED_TYPE_NAME