//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flyingpie.Storm.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Sql {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Sql() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Flyingpie.Storm.Resources.Sql", typeof(Sql).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///  p.SPECIFIC_SCHEMA AS SchemaName,
        ///  p.SPECIFIC_NAME AS StoredProcedureName,
        ///  p.PARAMETER_NAME AS ParameterName,
        ///  p.PARAMETER_MODE AS ParameterMode,
        ///  p.DATA_TYPE AS ParameterType,
        ///  p.USER_DEFINED_TYPE_SCHEMA AS UserDefinedTypeSchema,
        ///  p.USER_DEFINED_TYPE_NAME AS UserDefinedTypeName
        ///FROM INFORMATION_SCHEMA.ROUTINES r
        ///LEFT JOIN INFORMATION_SCHEMA.PARAMETERS p
        ///	ON r.SPECIFIC_SCHEMA = p.SPECIFIC_SCHEMA
        ///	AND r.SPECIFIC_NAME = p.SPECIFIC_NAME
        ///WHERE
        ///  p.SPECIFIC_NAME IS NOT NULL
        ///GROUP BY
        ///  p.SPECIFIC_S [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ListParameters {
            get {
                return ResourceManager.GetString("ListParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///  s.schema_id  AS SchemaId,
        ///  s.name       AS SchemaName
        ///FROM sys.schemas s
        ///INNER JOIN INFORMATION_SCHEMA.ROUTINES r ON s.name = r.SPECIFIC_SCHEMA
        ///WHERE
        ///  r.ROUTINE_TYPE = &apos;PROCEDURE&apos;
        ///GROUP BY
        ///  s.schema_id,
        ///  s.name.
        /// </summary>
        internal static string ListSchemas {
            get {
                return ResourceManager.GetString("ListSchemas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///  r.SPECIFIC_NAME AS StoredProcedureName,
        ///  r.SPECIFIC_SCHEMA AS SchemaName
        ///FROM INFORMATION_SCHEMA.ROUTINES r
        ///WHERE
        ///  r.ROUTINE_TYPE = &apos;PROCEDURE&apos;.
        /// </summary>
        internal static string ListStoredProcedures {
            get {
                return ResourceManager.GetString("ListStoredProcedures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///  tt.name &apos;UserDefinedTypeName&apos;,
        ///  c.column_id &apos;ColumnId&apos;,
        ///  c.name &apos;ColumnName&apos;,
        ///  t.name &apos;ColumnType&apos;,
        ///  s.name &apos;SchemaName&apos;
        ///FROM sys.table_types as tt
        ///INNER JOIN sys.columns as c
        ///  ON tt.type_table_object_id = c.object_id
        ///INNER JOIN sys.types t
        ///  ON c.system_type_id = t.system_type_id
        ///INNER JOIN sys.schemas s
        ///  ON tt.schema_id = s.schema_id
        ///WHERE t.name &lt;&gt; &apos;sysname&apos;.
        /// </summary>
        internal static string ListUserDefinedTypeColumns {
            get {
                return ResourceManager.GetString("ListUserDefinedTypeColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///  tt.name &apos;UserDefinedTypeName&apos;,
        ///  s.name &apos;SchemaName&apos;
        ///FROM sys.table_types as tt
        ///INNER JOIN sys.schemas s
        ///  ON tt.schema_id = s.schema_id.
        /// </summary>
        internal static string ListUserDefinedTypes {
            get {
                return ResourceManager.GetString("ListUserDefinedTypes", resourceCulture);
            }
        }
    }
}
